import os
import io
import base64
import tempfile
from pathlib import Path

import numpy as np
import streamlit as st
from PIL import Image, ImageDraw
from gtts import gTTS
from moviepy.editor import ImageClip, AudioFileClip

# ------------------------------------------------------------
# THE BELIEF MACHINE — Talking Avatar Chat
#
# This is a lightweight prototype:
#   1. User chats with the character.
#   2. A response is generated by the configured chat backend.
#   3. The response is converted to speech.
#   4. The portrait is turned into a short talking video.
#
# For production-grade lip-sync, replace make_talking_video()
# with LivePortrait, SadTalker, Wav2Lip, HeyGen, D-ID, etc.
# ------------------------------------------------------------

st.set_page_config(
    page_title="The Belief Machine — Talking Avatar",
    page_icon="✨",
    layout="centered",
)

AVATAR_PATH = Path("17080.png")


def simple_chat_reply(user_text: str) -> str:
    """
    Demo response engine.

    Replace this function with your preferred LLM API.
    Keeping it separate makes the avatar/video system reusable.
    """
    text = user_text.lower()

    if "belief machine" in text:
        return (
            "Welcome to The Belief Machine. I explore music, consciousness, "
            "science, spirituality, energy and the ideas that connect them."
        )

    if "hello" in text or "hi" in text:
        return "Hello. It's wonderful to meet you. What would you like to explore?"

    if "time" in text:
        return (
            "Time is fascinating because we experience it as a flow, while "
            "physics often describes it very differently. What part of time "
            "would you like to investigate?"
        )

    return (
        "That's an interesting question. Let's explore it together. "
        "Tell me a little more about what you are thinking."
    )


def text_to_speech(text: str, output_path: str):
    """Create an MP3 voice file using Google TTS."""
    tts = gTTS(text=text, lang="en", slow=False)
    tts.save(output_path)


def add_talking_effect(frame: Image.Image, mouth_open: float, zoom: float):
    """
    Lightweight animation effect.

    This does NOT perform true AI lip-sync. It creates a subtle
    camera movement and a mouth animation layer. For a real talking
    face, use LivePortrait/SadTalker/Wav2Lip or a hosted avatar API.
    """
    img = frame.copy().convert("RGB")

    # Gentle camera zoom.
    w, h = img.size
    crop_w = int(w / zoom)
    crop_h = int(h / zoom)
    left = (w - crop_w) // 2
    top = (h - crop_h) // 2
    img = img.crop((left, top, left + crop_w, top + crop_h))
    img = img.resize((w, h), Image.Resampling.LANCZOS)

    # Approximate mouth position for the supplied portrait.
    # The values are normalized so they scale with the image.
    mx = int(w * 0.515)
    my = int(h * 0.345)

    draw = ImageDraw.Draw(img, "RGBA")

    if mouth_open > 0.35:
        # Small dark opening + lower lip highlight.
        mw = int(w * (0.018 + mouth_open * 0.012))
        mh = int(h * (0.006 + mouth_open * 0.010))
        draw.ellipse(
            (mx - mw, my - mh, mx + mw, my + mh),
            fill=(45, 10, 15, 210),
        )
        draw.arc(
            (mx - mw, my - mh, mx + mw, my + mh),
            0, 180,
            fill=(220, 120, 120, 180),
            width=max(1, int(w * 0.0015)),
        )

    return img


def make_talking_video(image_path: str, audio_path: str, output_path: str):
    """
    Generate a short animated portrait video driven by audio volume.

    This is intentionally dependency-light. It produces:
      - subtle zoom/pan
      - audio-reactive mouth movement
      - synchronised voice

    Upgrade path:
      Replace this function with a neural lip-sync model.
    """
    audio = AudioFileClip(audio_path)
    duration = audio.duration

    source = Image.open(image_path).convert("RGB")
    fps = 24
    frame_count = max(1, int(duration * fps))

    # Read audio waveform for simple amplitude animation.
    try:
        samples = audio.to_soundarray(fps=2000)
        if samples.ndim == 2:
            samples = samples.mean(axis=1)
        samples = np.abs(samples)
        samples = samples / (samples.max() + 1e-9)
    except Exception:
        samples = np.ones(2000) * 0.3

    def frame_at_time(t):
        index = min(len(samples) - 1, int(t / duration * len(samples)))
        amp = float(samples[index])

        # Smooth-ish speaking movement.
        mouth = min(1.0, amp * 2.5)
        zoom = 1.0 + 0.018 * np.sin(t * 1.7)

        return np.array(add_talking_effect(source, mouth, zoom))

    clip = ImageClip(np.array(source)).set_duration(duration)

    # MoviePy asks for a frame function for dynamic imagery.
    clip = clip.fl(lambda gf, t: frame_at_time(t))
    clip = clip.set_audio(audio)

    clip.write_videofile(
        output_path,
        fps=fps,
        codec="libx264",
        audio_codec="aac",
        preset="medium",
        logger=None,
    )

    audio.close()
    clip.close()


# -------------------- UI --------------------

st.title("✨ The Belief Machine")
st.caption("A conversational talking-avatar prototype")

if not AVATAR_PATH.exists():
    st.error(
        "Place 17080.png (the supplied portrait) in the same folder as app.py."
    )
    st.stop()

if "messages" not in st.session_state:
    st.session_state.messages = []

if "video_path" not in st.session_state:
    st.session_state.video_path = None

# Avatar preview.
st.image(str(AVATAR_PATH), caption="The Belief Machine", use_container_width=True)

for message in st.session_state.messages:
    with st.chat_message(message["role"]):
        st.write(message["content"])

prompt = st.chat_input("Ask The Belief Machine something...")

if prompt:
    st.session_state.messages.append({"role": "user", "content": prompt})

    with st.chat_message("user"):
        st.write(prompt)

    with st.chat_message("assistant"):
        with st.spinner("Thinking..."):
            reply = simple_chat_reply(prompt)

        st.write(reply)

        with tempfile.TemporaryDirectory() as tmp:
            audio_path = os.path.join(tmp, "voice.mp3")
            video_path = os.path.join(tmp, "talking_avatar.mp4")

            with st.spinner("Creating voice and animation..."):
                text_to_speech(reply, audio_path)
                make_talking_video(
                    str(AVATAR_PATH),
                    audio_path,
                    video_path,
                )

            # Copy the result outside the temporary directory.
            final_video = os.path.abspath("talking_avatar.mp4")
            with open(video_path, "rb") as src, open(final_video, "wb") as dst:
                dst.write(src.read())

            st.session_state.video_path = final_video

        st.video(st.session_state.video_path)

        with open(st.session_state.video_path, "rb") as f:
            st.download_button(
                "Save response video",
                data=f.read(),
                file_name="the_belief_machine_response.mp4",
                mime="video/mp4",
            )

st.divider()

st.markdown(
    """
### How to turn this into a true AI talking character

The current prototype gives you a working chat → voice → animated-video
pipeline. The next upgrade is to replace the lightweight mouth effect with
a neural talking-head engine.

Recommended architecture:

**Chat message → LLM → response text → TTS voice → lip-sync model → video → chat UI**

For a much more realistic version, the `make_talking_video()` function can
be replaced by:

- **LivePortrait** — realistic portrait animation
- **Wav2Lip** — audio-driven lip synchronisation
- **SadTalker** — talking-head generation
- **HeyGen / D-ID** — hosted avatar APIs

You can also add microphone input so the user can speak to the character,
and WebSockets/WebRTC for near-real-time conversation.
"""
)

st.caption("Prototype created for The Belief Machine.")
